# Generated by Django 3.2.7 on 2021-09-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
